version: '3'
services:
  jenkins:
    image: jenkins/jenkins:2.440.1-lts-jdk21
    ports:
      - 8081:8080
    restart: always
    volumes:
      - /home/yingjie/deployment/jenkins_home:/var/jenkins_home
